### ISSUE TITLE
Socket hang up issue

### ISSUE THREAD

**Issue by supromikali** [fwouts/react-screenshot-test-example#14]
Hi @fwouts 

thank you for the nice lib, it seems to have a convenient API with multiple screen resolutions support and encapsulates the whole puppeteer/Docker setup problem making the testing easier, so I decided to give it a try. However I hit some issue while running the test for the first time: `Error: socket hang up` (I have posted the full error output below). 

My steps: clone the repo, npm install, npm run screenshot-test-local
My environment is: Ubuntu 16, Node 12

Could you have a look please?
```
/react-screenshot-test-with-create-react-app-master
> jest -c jest.screenshot.config.js

 FAIL  src/App.screenshot.jsx (10.426s)
  App
    Desktop
      ✕ app (5004ms)
    iPhone X
      ✕ app (5002ms)

  ● App › Desktop › app

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:141:25)

  ● App › iPhone X › app

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:141:25)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        10.445s
Ran all test suites.
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at Socket.socketOnEnd (_http_client.js:459:23)
    at Socket.emit (events.js:326:22)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketOnEnd (_http_client.js:459:9)
    at Socket.emit (events.js:326:22)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-screenshot-test-example@0.1.0 screenshot-test-local: `jest -c jest.screenshot.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-screenshot-test-example@0.1.0 screenshot-test-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2020-11-06T07_50_51_545Z-debug.log
```

**Comment by supromikali** [comment]
Closing as a duplicate to https://github.com/fwouts/react-screenshot-test/issues/286
